# Generated by Django 3.2.23 on 2025-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_parkingslot_is_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('staff', 'Staff'), ('guard', 'Guard')], default='guard', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
