# Generated by Django 3.2.23 on 2025-03-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_parkingslot_is_occupied'),
        ('app1', '0006_rename_last_updated_parkingslot_last_status_change'),
    ]

    operations = [
    ]
