# Generated by Django 3.2.23 on 2025-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_merge_20250312_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
