# Generated by Django 3.2.23 on 2025-02-28 14:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20250228_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
