version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.8
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
